export const LOGIN_USER = 'LOGIN_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_DETAILS = 'GET_DETAILS';

export const GET_WALLET = 'GET_WALLET';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';

export const SIGN_UP_CLEANER = 'SIGN_UP_CLEANER ';
export const APP_ERROR = 'APP_ERROR';

export const INTERNAL_ERROR = 'INTERNAL_ERROR';
export const CONFLICT_ERROR = 'CONFLICT_ERROR';
export const NOT_FOUND_ERROR = 'NOT_FOUND_ERROR';
export const NOTIFICATION = 'NOT_FOUND_ERROR';
export const FETCH_CLEANING_SCHEDULE = 'FETCH_CLEANING_SCHEDULE';
export const CANCEL_BOOKING = 'CANCEL_BOOKING';
export const FETCH_BOOKING = 'FETCH_BOOKING';
export const ADD_ITEM = 'ADD_ITEM';
export const ADD_DETAILS = 'ADD_DETAILS';
export const CHANGE_SETTINGS_LANGUAGE = 'CHANGE_SETTINGS_LANGUAGE';
export const FETCH_RATINGS = 'FETCH_RATINGS';
export const UPDATE_REQUEST = 'UPDATE_REQUEST';
/***
 *
 * APP_ERROR
 * NOTIFICATION FETCH_RATINGS
 *
 */
